language: node_js
dist: trusty
sudo: required
node_js: '6'
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
  - npm install -g bower polylint web-component-tester
  - bower install
  - polylint
  - chmod -R +x ./bower_components/git-version-tagging
script:
  - xvfb-run wct
after_success:
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GITHUB_TOKEN}:@github.com" > .git/credentials
  - if [ "${TRAVIS_BRANCH}" = "master" ] && [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then ./bower_components/git-version-tagging/create-release.sh; fi